sudo: required
language: generic 
services:
    - docker
before_install:
    - docker build -t truongatv/docker-react -f Dockerfile.dev . 
script:
    - docker run -e CI=true truongatv/docker-react npm run test